added getopts to the packageinstaller script and made each of my if statements a function to easily add them to the getopts

diff --git a/packageinstaller b/packageinstaller
--- a/packageinstaller
+++ b/packageinstaller
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 packagelist=" kakoune tmux neovim git"
 
 #checks if the effective user ID is 0 (which is the root user), learned about this through man sudo
@@ -12,65 +14,89 @@ USER_HOME="/home/$SUDO_USER"
 HOME=$USER_HOME
 
 
-#checks if the directory doesn't exist (! -d), and if it doesn't, then creates it
-if [[ ! -d ~/assignment2/project1 ]]; then 
-    echo "Attempting to create directories: assignment2/project1"
-    mkdir -p ~/assignment2/project1
-    if [[ $? -eq 0 ]]; then #checks if exit code of the recent command is equal to 0 (success)
-        echo "Exit code 0: Directories created successfully"
-    else
-        echo "Directory creation failed"
-        exit 1
-    fi
-    else 
-        echo "The directories already exist"
-fi
-
-
-#checks if the "packages" file exists (-f) in the specified path and if it does then checks if that file has the correct list. If the list is correct, the user can choose to install or not install the packages. If the list is not correct then it is overwritten with the correct list.
-if [[ -f ~/assignment2/project1/packages ]]; then 
-    echo "Package list has been found, now checking to see if the list is correct."
-    if [[ $(cat ~/assignment2/project1/packages) != $packagelist ]]; then
-        echo "Package list is incorrect...overwriting the correct list to the file."
-        cat > ~/assignment2/project1/packages <<- EOF
-$packagelist
-EOF
-        if [[ $? -eq 0 ]]; then
-            echo "Overwrite successful"
-            pacman -S $(cat ~/assignment2/project1/packages)
-        else 
-            echo "Overwriting package list did not work"
+create_directory() {
+    #checks if the directory doesn't exist, and if it doesn't, then creates it
+    if [[ ! -d ~/assignment2/project1 ]]; then 
+        echo "Attempting to create directories: assignment2/project1"
+        mkdir -p ~/assignment2/project1
+        if [[ $? -eq 0 ]]; then #checks if exit code of the recent command is 0 (success)
+            echo "Exit code 0: Directories created successfully"
+        else
+            echo "Directory creation failed"
             exit 1
         fi
-    else
-        echo "Package list exists and is correct!!! everything should be installed already"
-        read -p "However, would you like to install the packages again? [Y/n]: " character #this is for if the user didn't want to install the packages the first time, but the directory and file exists. they can choose to download.
-        case "$character" in
-            Y|y)
-                echo "installing the packages..."
-                pacman -S $packagelist
-                ;;
-            N|n)
-                echo "ok.."
-                ;;
-            *)
-                echo "you did not enter y or n"
-                ;;
-        esac     
+        else 
+            echo "The directories already exist"
     fi
-fi
+}
 
-#this checks if the packages file does not exist
-if [[ ! -f ~/assignment2/project1/packages ]]; then
-    echo "Package list not found. Attempting to create the package list and install packages."
-    cat > ~/assignment2/project1/packages <<- EOF 
-$packagelist
+
+
+#checks if the "packages" file exists in the specified path and if it does then checks if that file has the correct list. If the list is correct, the user can choose to install or not install the packages. If the list is not correct then it is overwritten with the correct list.
+overwrite_or_install_packages() {
+    if [[ -f ~/assignment2/project1/packages ]]; then 
+        echo "Package list has been found, now checking to see if the list is correct."
+        if [[ $(cat ~/assignment2/project1/packages) != $packagelist ]]; then
+            echo "Package list is incorrect...overwriting the correct list to the file."
+            cat > ~/assignment2/project1/packages <<- EOF
+    $packagelist
 EOF
-    if [[ $? -eq 0 ]]; then
-        echo "Exit code: 0, Package list created successfully"
-        pacman -S $(cat ~/assignment2/project1/packages) #installs the packages, using command substitution to read the contents of the packages file
-    else
-        echo "Package list creation failed"
-        exit 1
+            if [[ $? -eq 0 ]]; then
+                echo "Overwrite successful"
+                pacman -S $(cat ~/assignment2/project1/packages)
+            else 
+                echo "Overwriting package list did not work"
+                exit 1
+            fi
+        else
+            echo "Package list exists and is correct!!! everything should be installed already"
+            read -p "However, would you like to install the packages again? [Y/n]: " character #this is for if the user didn't want to install the packages the first time, but the directory and file exists. they can choose to download.
+            case "$character" in
+                Y|y)
+                    echo "installing the packages..."
+                    pacman -S $packagelist
+                    ;;
+                N|n)
+                    echo "ok.."
+                    ;;
+                *)
+                    echo "you did not enter y or n"
+                    ;;
+            esac     
+        fi
     fi
-fi
+}
+create_and_install_packages() {
+#this checks if the packages file does not exist
+    if [[ ! -f ~/assignment2/project1/packages ]]; then
+        echo "Package list not found. Attempting to create the package list and install packages."
+        cat > ~/assignment2/project1/packages <<- EOF 
+    $packagelist
+EOF
+        if [[ $? -eq 0 ]]; then
+            echo "Exit code: 0, Package list created successfully"
+            pacman -S $(cat ~/assignment2/project1/packages)
+        else
+            echo "Package list creation failed"
+            exit 1
+        fi
+    fi
+}
+
+
+while getopts ":abc" opt; do
+    case $opt in
+        a)
+            create_directory
+            ;;
+        b)
+            overwrite_or_install_packages
+            ;;
+        c)
+            create_and_install_packages
+            ;;
+        ?)
+            echo "Invalid option: '$OPTARG', please type a, b, or c"
+            ;;
+    esac
+done
